import { config } from 'dotenv';

config();

const ENV_VARS = {
  WEBHOOK_VERIFY_TOKEN: process.env.WEBHOOK_VERIFY_TOKEN || "pollohook2026",
  GRAPH_API_TOKEN: process.env.GRAPH_API_TOKEN || "EAARsh9tdbmoBPJb4q5jBBRaehLIjIfTw2CGelJBTZCuDwkSwBdf5nPWc62bb3hEJ3sPZA487zAAhuDFkJz0ZCYOterbeuKyR7JDBTLZATIhTh0UHKpZAOPL37mXCyXbIQwwHmUwzaPHW2aJQAhJeZCLlRCXxkRM1MNBFfmQeKggfguJdhhSidAXa78LlBdZAQZDZD",
  PORT: process.env.PORT || "5200",
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  GEMINI_MODEL: process.env.GEMINI_MODEL,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY_ID: process.env.FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID: process.env.FIREBASE_CLIENT_ID,
  FIREBASE_AUTH_URI: process.env.FIREBASE_AUTH_URI,
  FIREBASE_TOKEN_URI: process.env.FIREBASE_TOKEN_URI,
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL: process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
  FIREBASE_CLIENT_X509_CERT_URL: process.env.FIREBASE_CLIENT_X509_CERT_URL,
  FIREBASE_UNIVERSE_DOMAIN: process.env.FIREBASE_UNIVERSE_DOMAIN,
  BUCKET_PROJECT_ID: process.env.BUCKET_PROJECT_ID,
  BUCKET_PRIVATE_KEY_ID: process.env.BUCKET_PRIVATE_KEY_ID,
  BUCKET_PRIVATE_KEY: process.env.BUCKET_PRIVATE_KEY,
  BUCKET_CLIENT_EMAIL: process.env.BUCKET_CLIENT_EMAIL,
  BUCKET_CLIENT_ID: process.env.BUCKET_CLIENT_ID,
  BUCKET_AUTH_URI: process.env.BUCKET_AUTH_URI,
  BUCKET_TOKEN_URI: process.env.BUCKET_TOKEN_URI,
  BUCKET_AUTH_PROVIDER_X509_CERT_URL: process.env.BUCKET_AUTH_PROVIDER_X509_CERT_URL,
  BUCKET_CLIENT_X509_CERT_URL: process.env.BUCKET_CLIENT_X509_CERT_URL,
  BUCKET_UNIVERSE_DOMAIN: process.env.BUCKET_UNIVERSE_DOMAIN
};

export default ENV_VARS;